#!/bin/bash
# Chromebrew container startup script.
# Author: Satadru Pramanik (satmandu) satadru at gmail dot com
CONTAINER_ARCH="$(file /bin/bash | awk '{print $7}' | sed 's/,//g')"
PASSTHROUGH_ARCH="$(uname -m)"
if [ -n "$LOCALRC" ]; then echo "LOCALRC is $LOCALRC" ; fi
echo "CONTAINER_ARCH: $CONTAINER_ARCH"
echo "PASSTHROUGH_ARCH: $PASSTHROUGH_ARCH"
default_container_cmd="/usr/bin/sudo -i -u chronos"

case $CONTAINER_ARCH in

  x86-64)
    exec $default_container_cmd
    ;;

  Intel)
    setarch_container_cmd="/usr/local/bin/setarch i686 sudo -i -u chronos"
    [[ "${PASSTHROUGH_ARCH}" == "i686" ]] && exec $default_container_cmd
    [[ "${PASSTHROUGH_ARCH}" == "x86_64" ]] && exec $setarch_container_cmd
    ;;

  ARM)
    setarch_container_cmd="/usr/local/bin/setarch armv7l sudo -i -u chronos"
    [[ "${PASSTHROUGH_ARCH}" =~ ^(armv7l|armv8l)$ ]] && exec $default_container_cmd
    [[ "${PASSTHROUGH_ARCH}" == 'aarch64' ]] && exec $setarch_container_cmd
    ;;

  *)
    echo "Chromebrew container startup script fallthrough option..."
    exec /bin/bash
    ;;
esac
